### PR TITLE
Show days with no sales in graph

### PR DESCRIPTION
**Pull request by ajgeiss0702**
Will show days without sales in the graph instead of skipping them

### CODE REVIEW

**Comment by rodel77** [comment]
I spend a lot of time without selling stuff so that's why I made the skipping thing just to take track of sales combos. I think a good solution would be to add this like an option so people can use skipping only if they want.

Brianna made an option to save your resources page as a shortcut so it's a good idea to copy that. I'll do it soon(TM) unless you want to do it!

**Comment by ajgeiss0702** [comment]
Sure, ill do it :)

**Comment by ajgeiss0702** [comment]
Done :)

**Comment by rodel77** [comment]
Looks good! Thanks ;)

**Pull request merged**
